baseURL = "http://jeremypnauta.com/"
languageCode = "en-us"
title = "Jeremy Nauta"
# disqusShortname = ""
# googleAnalytics = ""

[params]
    author = "Jeremy Nauta"
    accent = "#FFB000"
    accent2 = "#1dbbd6"
    showBorder = false
    backgroundColor = "white"
    font = "Open Sans" # should match the name on Google Fonts!
    dateFormat = "January 2, 2006"

[[menu.main]]
    url = "/about-me/"
    name = "About Me"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:jeremypnauta@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jpnauta/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://bitbucket.org/jpnauta/"
    name = "bitbucket"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/jeremy-nauta-01b65680/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://twitter.com/JeremyNauta/"
    name = "twitter"
    weight = 5
